services:
  - type: web
    name: gemini_ai_new_bot # Можете дать любое имя
    env: python
    plan: free # Важно для бесплатных лимитов
    buildCommand: "python -m pip install --upgrade pip && pip install -r requirements.txt --upgrade"
    startCommand: "python ./main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: GEMINI_WEBHOOK_PATH
        sync: false
      - key: DATABASE_URL
        sync: false
