services:
  - type: web
    name: gemini-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: GEMINI_WEBHOOK_PATH
        sync: false
    build:
      apt:
        packages:
          - tesseract-ocr
          # ===== ИСПРАВЛЕНИЕ: Добавляем языковые пакеты для Tesseract =====
          - tesseract-ocr-eng
          - tesseract-ocr-rus
          # ================================================================
